### ISSUE TITLE
Chat messages gets hidden when opening the keyboard on app

### ISSUE THREAD

**Issue by ankitbhattsdd** [livechat/react-native-livechat#10]
When i open the keyboard then the previous app gets hidden instead of floating upwards.

<KeyboardAwareScrollView style={{ backgroundColor: 'white' }} keyboardShouldPersistTaps={'always'}>
< LiveChat bubbleColor = '#E18C50'
license={} bubbleLeft={w * .75} onLoaded={ref => this.livechat = ref} style={{ height: h * .5 }}
bubbleTop={h * .8} bottomOffset={h * .5} />
![43839563-0b044710-9b3c-11e8-87fc-b6c4ac41969c](https://user-images.githubusercontent.com/32154346/44529667-47263d00-a70a-11e8-84e7-63fe02087220.png)

**Comment by venits** [comment]
Our bubble has position `absolute`. It is desired solution because we don't want our bubble to interact with user View at any point.
