### ISSUE TITLE
Having trouble with chat connection

### ISSUE THREAD

**Issue by NikosPapadakos** [livechat/react-native-livechat#103]
Hey there,
I've created an app in the console, got the module from npm,
imported the module and called the module with license id, client id and redirectUrl provided from the console.
The chat wont connect to the app.

I get these logs when i open the chat's page.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/74835922/186150485-58092cae-2a14-4ad3-abd5-35e34556e116.png">

This is my code 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/74835922/186151250-94012a70-c5b7-4af7-b053-c60fcbc2285c.png">

this is what i get in the emulator
<img width="323" alt="image" src="https://user-images.githubusercontent.com/74835922/186151541-7e4a0b1d-e888-456e-a0f2-47ef837286a9.png">

Thanks in advance

**Comment by walaszczykm** [comment]
Hello @NikosPapadakos 👋 
Thanks for the report. Sad to hear you have encountered an issue.

We have investigated the issue, and it looks like we just need to stop relying on one of the deprecated dependencies. I have prepared the PR https://github.com/livechat/react-native-livechat/pull/104. As soon as it will be merged, we are going to release the update on npm 🙂

**Comment by walaszczykm** [comment]
Changes have been published to npm with version: [2.1.1](https://www.npmjs.com/package/react-native-livechat/v/2.1.1)

**Comment by NikosPapadakos** [comment]
Ok thanks a lot Ill have a look later on the upcoming week.
