### ISSUE TITLE
LiveChat component gets in a state where sendMessage hangs.

### ISSUE THREAD

**Issue by mitya777** [livechat/react-native-livechat#13]
Sometimes I type a message and press send and nothing happens.

I forked the code and added console logs around the handleSend method: https://github.com/livechat/react-native-livechat/blob/master/LiveChat/Chat/Chat.js#L89

Something like this: 
`
handleSend = (messages) => {
    console.log('sending')
    GLOBAL.visitorSDK.sendMessage({
      customId: String(Math.random()),
      text: messages[0].text,
    }).then(response => {
        console.log(response)
    }).catch(error => {
        console.log(error)
    });
};
`

I see that the method gets called, but no response or error is returned.

P.S. not sure why code not formatting properly.

**Comment by mitya777** [comment]
The app is running inside Expo app.

**Comment by venits** [comment]
It may be problem with Visitor Sdk itself. Sometimes it fails to connect via Websocket with our server. I will inform our team about this.
