### ISSUE TITLE
Vistors unable to see their queue line or notificationt that an agent is currently talking to them

### ISSUE THREAD

**Issue by raihanmasroor** [livechat/react-native-livechat#16]
There is a missing feature for which visitors are unable to see their queue position. If agents are currently busy, the experience feels is that visitors don't see anything and think that chat is broken or nobody is responding.

Furthermore, if chat is assigned to an agent, visitors are not shown that.

**Comment by venits** [comment]
Hi,

To make this work you have to use: https://developers.livechatinc.com/docs/visitor-sdk/#visitor-queued   With this callback you will receive information if user is queued or not. In case user goes to queue you should display component with useful information for visitor.
