### ISSUE TITLE
does not work on android

### ISSUE THREAD

**Issue by mineralmarketusa** [livechat/react-native-livechat#2]
nothing happens when clicking on the bubble icon.
on Samsung Galaxy note 8

It works okay on iPhone.
Can get any advice?

<environment>
expo 22.0.4
react-native 0.49

**Comment by mineralmarketusa** [comment]
please disregard this. It seems to be working okay now. it was something with the container styling. closing it now.

**Comment by afilp** [comment]
@mineralmarketusa I have the same problem. I click the bubble and nothing happens (Android).

Any ideas what may cause this?

I am also using `react-native-drawer`, could it be this?

Thanks!

**Comment by mitya777** [comment]
Same problem on Note 8. I had to pass ```<LiveChat move={false}>``` to get it to work.
