### ISSUE TITLE
Crash in Android due to `GLOBAL.cookie` and object not found

### ISSUE THREAD

**Issue by afilp** [livechat/react-native-livechat#25]
The mobile app crashes in Android when entering the chat screen due to an error related to `GLOBAL.cookie` and object not found.

What should we do? We use the latest react-native, latest chat library and latest gradle.

Thanks!

**Comment by venits** [comment]
Hi,
you can define `GLOBAL.cookie = {}` somewhere in your code, before loading LiveChat component

**Comment by afilp** [comment]
@venits Thanks, is this a known issue? Because I did not have this before. Not sure what exactly changed now, because I made a lot of upgrades (`react-native`, `gradle`, etc.).

**Comment by venits** [comment]
Hmm it is little strange because module itself defines `GLOBAL.cookie = {}` so it should work ;/
I will take closer look at this issue

**Comment by afilp** [comment]
@venits To help you, this is what we get when it crashes:

![image](https://user-images.githubusercontent.com/7850073/52526551-b85eaa00-2cc2-11e9-9ccc-fea69fb1e447.png)

**Comment by afilp** [comment]
@venits Not sure why it is closed, did you happen to take a closer look? Thanks!

**Comment by venits** [comment]
Hi, is this problem still appears when you put `GLOBAL.cookie = {}` before importing our component?

**Comment by afilp** [comment]
The problem still appears, I put it everywhere.

Note that I am using the "react-native-webview", `webview` has been removed from `react-native`. Not sure if this affects somehow.

**Comment by afilp** [comment]
Also, it should not be `GLOBAL.cookie = {}` but `GLOBAL.cookie = ""`.

I put it expclicitly here just for **test** and it moved forward:

```
var tv = ev, rv = function (r) {
        debugger;
        GLOBAL.cookie = '';
        var e = GLOBAL.cookie.split(";"), t = tv(function (e) {
            var t = Hs(e).split("=");
            return decodeURIComponent(t[0]) === r
        }, e);
        return t ? decodeURIComponent(t.split("=")[1]) : null
    }, nv = regeneratorRuntime.mark(av);
```

Obviously, this is not a solution, I just give a hint here.

Then, we get a new warning (not error):

```
ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information
```

**Comment by afilp** [comment]
Can you please make a release that also fixes this issue? Thanks a lot!
