### ISSUE TITLE
Can't use <LiveChat> tag

### ISSUE THREAD

**Issue by zhao0423** [livechat/react-native-livechat#3]
i did following steps:
import LiveChat from 'react-native-livechat'

http://prntscr.com/idp4hy

by the way, i got this error
TypeError: document.getElementsByTagName is not a function

This error is located at:
    in LiveChat (at LiveChatPage.js:11)
    in LiveChatPage (at navigationStore.js:319)
    in Wrapped (at SceneView.js:31)
    in SceneView (at CardStack.js:412)
    in RCTView (at View.js:71)
    in View (at CardStack.js:411)
    in RCTView (at View.js:71)
    in View (at CardStack.js:410)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:71)
    in View (at CardStack.js:383)
    in RCTView (at View.js:71)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:71)

**Comment by venits** [comment]
Hi, the problem might be not in 'react-native-livechat' because in whole module I am not using **document** even once. Can you replace <LiveChat> with for example simple <View> just to check if problem still appears?

**Comment by zhao0423** [comment]
http://prntscr.com/idpfpj

i think that's very simple code.

**Comment by zhao0423** [comment]
thanks it works.
