### ISSUE TITLE
import @livechat/livechat-visitor-sdk/ does not work and generates error

### ISSUE THREAD

**Issue by saqygee** [livechat/react-native-livechat#31]
`error: bundling failed: Error: While trying to resolve module `@livechat/mitt` from file `/root/pg7Mob/node_modules/@livechat/livechat-visitor-sdk/dist/index.cjs.js`, the package `/root/pg7Mob/node_modules/@livechat/mitt/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/root/pg7Mob/node_modules/@livechat/mitt/dist/livechat-mitt.native.js`. Indeed, none of these files exist:

  * `/root/pg7Mob/node_modules/@livechat/mitt/dist/livechat-mitt.native.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/root/pg7Mob/node_modules/@livechat/mitt/dist/livechat-mitt.native.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/root/pg7Mob/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/root/pg7Mob/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/root/pg7Mob/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/root/pg7Mob/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/root/pg7Mob/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /root/pg7Mob/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/root/pg7Mob/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/root/pg7Mob/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)

`

Hi I am trying to integrate simple chat into  the module but just a simple import breaks the whole project and gives the above error whats wrong with it.

**Comment by venits** [comment]
Hi,
can you try adding this file to your project:
https://github.com/livechat/react-native-livechat/blob/master/LiveChat/livechat-visitor-sdk.min.js
instead of importing VisitorSdk from LiveChat. The LiveChat module itself is not mobile friendly :/

**Comment by saqygee** [comment]
thanks for replying to be more clear so you mean instead of importing i add it inside <script></script> tags

**Comment by venits** [comment]
Hi it should be more like this:
`
import {init} from './sdk/livechat-visitor-sdk.min';
`

**Comment by saqygee** [comment]
thanks I will test it and let you know

**Comment by saqygee** [comment]
I have tried using that approach it gives me another error says 
TypeError: undefined is not an Object (evaluating 'Global.cookie.split')  

please do remember I am using react native all I want to achieve is to set customer name and remove title from the window because i have my own back button or if I can manipulate your back button it would be really awesome that will save me 100 hours to develop something from ground zero.

Thank you

**Comment by venits** [comment]
Hi, please set somewhere in your code:
`Global.cookie = ''`
and make it before importing visitorSDK

**Comment by saqygee** [comment]
that worked like charm thanks Ventis. I hope in future this sdk more user friendly and add more features to chat widget like remove title bar, full screen windows as default feature, remove bubble. etc

**Comment by afilp** [comment]
Related issue: https://github.com/livechat/react-native-livechat/issues/25

Asking there if there will be a release with fixes on this issue. Thanks!
