### ISSUE TITLE
Callback 'agent_changed' fires half of the time. Resulting in message not being send.

### ISSUE THREAD

**Issue by semammerlaan** [livechat/react-native-livechat#36]
Half of the time the chat is not sending message. It seems the callback 'agent_changed' is not always firing. Resulting in messages not being send to Livechat. You got any idea?

**Comment by venits** [comment]
Hi, this library uses old Visitor SDK that have many errors and is not mobile friendly. There is no much you can do right now :( But we are planning to release new version of Visitor SDK that will be more adapted to mobile. It should be available within 2 months.

**Comment by semammerlaan** [comment]
Allright, thanks for the fast response! There is nothing we can do?

**Comment by venits** [comment]
It should work when you are chatting with one agent but when agent has changed it probably not handles it properly.
