### ISSUE TITLE
this is not working in run mode

### ISSUE THREAD

**Issue by zhao0423** [livechat/react-native-livechat#4]
Hello, everyone.
I am using livechat.
btw, this is working fine in debug mode, but not in run mode.
this is my result screen in debug mode.
http://prntscr.com/ids41q

i got this error in run mode
http://prntscr.com/idrmfe
Please help me.

**Comment by venits** [comment]
Hi, In 'run mode' you mean when you build app for production?

**Comment by zhao0423** [comment]
Yes.

**Comment by venits** [comment]
I found out that problem is with 'livechat-visitor-sdk' which this module is using. It is simply not adapted for mobile development. I will inform other team about that and hope they will fix it soon :)

**Comment by zhao0423** [comment]
Thanks for you help. Please let me know if they fix
