### ISSUE TITLE
import LivechatVisitorSDK from '@livechat/livechat-visitor-sdk' not working

### ISSUE THREAD

**Issue by gev13** [livechat/react-native-livechat#47]
I have imported

import LivechatVisitorSDK from '@livechat/livechat-visitor-sdk';
const visitorSDK = LivechatVisitorSDK.init({ license: xxxxxxx, group: 0, })

after that getting this error:

"Cannot read property 'init' of undefined".

before this import I have tried to import by this method:

import * as LivechatVisitorSDK from '@livechat/livechat-visitor-sdk';
const visitorSDK = LivechatVisitorSDK.init({ license: xxxxxxx, group: 0, })

after that get this error:

"document is not defined"

Please help!

**Comment by jigarvyas** [comment]
@gev13 I'm facing something very similar; please share what solution worked for you since you've closed this issue
