### ISSUE TITLE
Crash while using React Native  0.61.1 because of Gifted Chat

### ISSUE THREAD

**Issue by basilaiman** [livechat/react-native-livechat#56]
While using the package on React Native version 0.61.1. I got an exception in GiftedChat the package. 
here is a screenshot
![Screenshot_6](https://user-images.githubusercontent.com/16269418/69905850-93a70080-13c2-11ea-845d-fae57e45b52e.png)

**Comment by konradk** [comment]
The issue has been fixed in the latest version `2.0.0-6`
