### ISSUE TITLE
Error when sending message in chat

### ISSUE THREAD

**Issue by johnryan** [livechat/react-native-livechat#65]
Hi, I'm trying to set up livechat in an app:

```
<LiveChat greeting="Welcome to Chat!" license="########" />
```

The button renders correctly and opens the chat ui but when I send a message I get this error: 

![Simulator Screen Shot - iPhone 11 - 2020-06-02 at 09 42 04](https://user-images.githubusercontent.com/416564/83527287-98558a00-a4b5-11ea-9f6a-df8ab703163f.png)

Can you advise what I might be doing wrong?

**Comment by Coder108** [comment]
Is this problem solved? I also encountered the same problem

**Comment by johnryan** [comment]
I'm not sure, I switched to using Intercom.
