### ISSUE TITLE
The following problems will occur when running for the first time, causing the app to crash

### ISSUE THREAD

**Issue by Coder108** [livechat/react-native-livechat#72]
![WX20200721-114747](https://user-images.githubusercontent.com/30209569/88010792-4f7e9100-cb48-11ea-9c5f-951f263338ae.png)
@konradk @venits  thx~

**Comment by Coder108** [comment]
Hello, have you encountered this problem?
![WX20200721-114747](https://user-images.githubusercontent.com/30209569/88019951-a56b1e80-cadf-11ea-8f35-36f912591377.png)
Mine is after this problem occurred and after ignoring it, the problem similar to your sdk appeared

**Comment by kelvinaliyanto** [comment]
I encounter the same error. Any fix on this? thanks

**Comment by Coder108** [comment]
> I encounter the same error. Any fix on this? thanks

I switched to using webview to implement chat, because the problem of this library has not been solved yet, it is very bad and has not been solved yet

**Comment by joaohedy** [comment]
Check this one: https://github.com/livechat/react-native-livechat/issues/84#issuecomment-734337699
