### ISSUE TITLE
Need to open chat when component loads, documentation has only closeChat method.

### ISSUE THREAD

**Issue by bhargavb07** [livechat/react-native-livechat#8]
I want to start the chat when my help.js component loads, without displaying the bubble.
But I am not able to figure it out as the documentation says it has only closeChat method and no openChat method.

CODE:
```
import React, { Component } from 'react';
import LiveChat from 'react-native-livechat';

export default class Help extends Component {

  componentDidMount() {
    this.livechat.startChat();
  }

  render() {
    return (
        <LiveChat
        license={XXXXXX}
        onLoaded={ref => (this.livechat = ref)}
        />
    );
  }
}
```

**Comment by saitbnzl** [comment]
This module is really useless without this function.

**Comment by saitbnzl** [comment]
I've solved this by exporting Chat.js in my project from index.js of this module:

`import ChatBubble from './LiveChat/ChatBubble/ChatBubble';
import Chat from './LiveChat/Chat/Chat';
import LiveChat from './LiveChat/LiveChat';

export { LiveChat, Chat, ChatBubble };
`
But it needs extra work after that, lots of extra work.

**Comment by venits** [comment]
Yes It requires a lot of work. It will be better to create this solution from scratch. Here is documentation I were using to create this module: https://developers.livechatinc.com/docs/visitor-sdk/#methods
