### ISSUE TITLE
I need to open the chat without the bubble, when the component loads

### ISSUE THREAD

**Issue by sndkd** [livechat/react-native-livechat#9]
How to disable the bubble and allow only the Livechat component to be shown?

**Comment by venits** [comment]
It is possible but you need to make changes in code. I would recommend to check: https://developers.livechatinc.com/docs/visitor-sdk/#methods  . Here you can find everything you need :)

**Comment by peconia** [comment]
We found out you can hide the bubble and then open the chat without a real click.
   
     // in the component render, add a ref into the Livechat and hide the bubble
    <LiveChat
          license={111111}
          ref={a => (this.liveChat = a)}
          bubble={<View style={{ Background: "transparent" }} />}
        />

When the ref has been added, you can call to open the chat when needed:

    this.liveChat.openChat();
